import * as Sentry from '@sentry/node'
import Fastify from 'fastify'
import cors from '@fastify/cors'
import pg from '@fastify/postgres'
import { subnetRoutes } from './subnet-routes.js'

/**
 * @param {object} args
 * @param {string} args.databaseUrl
 * @param {import('pg').PoolConfig} args.dbPoolConfig
 * @param {Fastify.FastifyLoggerOptions} args.logger
 * @returns
 */
export const createApp = ({ databaseUrl, dbPoolConfig, logger }) => {
  const app = Fastify({ logger })
  Sentry.setupFastifyErrorHandler(app)

  app.register(cors, {
    origin: [
      'http://localhost:3000',
      'https://leaderboard.checker.network',
      'https://leaderboard-f1i.pages.dev',
      // Allow all subdomains of leaderboard-f1i.pages.dev
      // generated by Cloudflare Pages preview deployments
      /^https:\/\/[^.]+\.leaderboard-f1i\.pages\.dev$/
    ]
  })
  app.register(pg, { ...dbPoolConfig, connectionString: databaseUrl })
  app.get('/', async function handler (request, reply) {
    return 'OK'
  })

  app.register(subnetRoutes)
  return app
}
